apiVersion: v1
kind: List
items:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: react-jobs
      namespace: baqe-jobs-dashboards
      labels:
        project: react-jobs
        version: 0.1.0
        provider: nodeshift
        app: react-jobs
        app.kubernetes.io/name: nodejs
        app.kubernetes.io/component: react-jobs
        app.kubernetes.io/instance: react-jobs
        app.openshift.io/runtime: nodejs
      annotations:
        nodeshift/git-branch: master
        nodeshift/git-commit: 122388cb9c92c9f5a0a2709da0c3e991bced0e1b
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: react-jobs
        project: react-jobs
        provider: nodeshift
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - react-jobs
            from:
              kind: ImageStreamTag
              namespace: baqe-jobs-dashboards
              name: 'react-jobs:latest'
      template:
        metadata:
          labels:
            project: react-jobs
            version: 0.1.0
            provider: nodeshift
            app: react-jobs
          annotations:
            nodeshift/git-branch: master
            nodeshift/git-commit: 122388cb9c92c9f5a0a2709da0c3e991bced0e1b
        spec:
          containers:
            - image: react-jobs
              name: react-jobs
              securityContext:
                privileged: false
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              env: []
  - apiVersion: v1
    kind: Service
    spec:
      selector:
        project: react-jobs
        provider: nodeshift
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          name: http
      type: ClusterIP
    metadata:
      name: react-jobs
      namespace: baqe-jobs-dashboards
      labels:
        project: react-jobs
        version: 0.1.0
        provider: nodeshift
        app.kubernetes.io/name: nodejs
        app.kubernetes.io/component: react-jobs
        app.kubernetes.io/instance: react-jobs
        app.openshift.io/runtime: nodejs
      annotations:
        nodeshift/git-branch: master
        nodeshift/git-commit: 122388cb9c92c9f5a0a2709da0c3e991bced0e1b
  - apiVersion: route.openshift.io/v1
    kind: Route
    spec:
      to:
        kind: Service
        name: react-jobs
      port:
        targetPort: 8080
    metadata:
      name: react-jobs
      labels:
        project: react-jobs
        version: 0.1.0
        provider: nodeshift
        app.kubernetes.io/name: nodejs
        app.kubernetes.io/component: react-jobs
        app.kubernetes.io/instance: react-jobs
        app.openshift.io/runtime: nodejs
